language: scala
jdk:
  - oraclejdk8
scala:
  - 2.12.8
before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
  - "$HOME/.sbt/cache"
  - "$HOME/.sbt/1.0"
  - "$HOME/.sbt/boot/"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.ivy2"
before_install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_8d91199f8619_key -iv $encrypted_8d91199f8619_iv -in secring.gpg.enc -out secring.gpg -d; fi
install:
  - rvm use 2.3.0 --install --fuzzy
  - gem install sass
  - gem install jekyll -v 3.2.1
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport coverageAggregate docs/tut
  - bash <(curl -s https://codecov.io/bash)
stages:
- test
- plugin
- deploy
- microsite
jobs:
  include:
    - stage: plugin
      script:
        - sbt ++$TRAVIS_SCALA_VERSION sbt-hood-plugin/test
        - sbt ++$TRAVIS_SCALA_VERSION sbt-hood-plugin/scripted
    - stage: deploy
      if: branch = master AND type != pull_request
      script:
        - if grep -q "SNAPSHOT" version.sbt; then
            sbt +publish;
            sbt sbt-hood-plugin/publish;
          else
            sbt orgUpdateDocFiles;
            git reset --hard HEAD;
            git clean -f;
            git checkout master;
            git pull origin master;
            sbt ";project sbt-hood-plugin;release";
            sbt release;
          fi
    - stage: microsite
      if: branch = master AND type != pull_request
      script:
        - if grep -q "SNAPSHOT" version.sbt; then
            echo "Skipping microsite publication, snapshot version";
          else
            echo "Not ready yet! (sbt docs/publishMicrosite)";
          fi
